# example values

indexing-settings:
  sites:
    - url: https://sendel.ru
      name: Konstantin Shibkov
#    - url: https://lenta.ru
#      name: Лента.ру
    - url: https://skillbox.ru
      name: Skillbox – образовательная платформа с онлайн-курсами
    - url: https://playback.ru
      name: Интернет-магазин PlayBack.ru
    - url: https://rostov.store123.ru
      name: STORE123 - цифровая техника по низким ценам
#    - url: https://volochek.life
#      name: Вышний Волочёк
#    - url: https://www.radiomv.ru
#      name: Милицейская волна
#    - url: https://www.lutherancathedral.ru
#      name: LutheranCathedral.ru
#    - url: https://dimonvideo.ru
#      name: DimonVideo##

server:
  port: 8080

spring:
  datasource:
    username: rootuser
    password: rootroot
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect